version : "3.8"
services :
  tourGuide :
    image : tourguide-docker
    ports :
      - "127.0.0.1:8081:8080"
    depends_on:
      gpsUtil:
        condition: service_started
      #rewardsCentral:
      #  condition: service_started
      #tripPricer:
      #  condition: service_started

  gpsUtil:
    image : gpsutil-docker
    ports :
      - "127.0.0.1:8090:8090"

  #rewardsCentral:
  #  image: rewardscentral-docker
  #  ports :
  #    - "127.0.0.1:8091:8091"

  #tripPricer :
  #  image : trippricer-docker
  #  ports:
  #    - "127.0.0.1:8092:8092"

###https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211677-creez-un-fichier-docker-compose-pour-orchestrer-vos-conteneurs
###https://dev.to/azure/how-you-can-learn-docker-from-the-beginning-covers-docker-compose-volumes-databases-in-the-cloud-and-much-more-8mg