# https://hub.docker.com/_/openjdk
FROM openjdk:11
LABEL administrator="kyle10_dev@outlook.fr"
#EXPOSE 8081:8080
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/tourGuide.jar"]


# https://mkyong.com/docker/docker-and-java-application-examples/
# https://spring.io/guides/topicals/spring-boot-docker/